<a href="https://colab.research.google.com/github/akifnawab038/ASSIGNMENT-NUMPY/blob/main/ASSIGNMENT_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ASSIGNMENT
  # NUMPY:

### Practical questions

**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns**

In [1]:
import numpy as np


array = np.random.randint(1, 101, (3, 3))

print("Original array:")
print(array)

interchanged_array = array.T

print("\nInterchanged array:")
print(interchanged_array)

Original array:
[[72 80 54]
 [59 49  1]
 [24 42  8]]

Interchanged array:
[[72 59 24]
 [80 49 42]
 [54  1  8]]


**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array**

In [2]:
import numpy as np

arr = np.arange(10)

arr_2x5 = arr.reshape(2, 5)
print("2x5 array:\n", arr_2x5)

arr_5x2 = arr.reshape(5, 2)
print("5x2 array:\n", arr_5x2)

2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [5]:
import numpy as np

arr = np.random.rand(4, 4)

arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("4x4 array:\n", arr)
print("6x6 array with border:\n", arr_with_border)

4x4 array:
 [[0.15586777 0.04910273 0.4253007  0.32749008]
 [0.66269189 0.53867361 0.73980084 0.26925793]
 [0.71145392 0.46609582 0.40620573 0.74380881]
 [0.50067306 0.41220718 0.94258054 0.64667963]]
6x6 array with border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.15586777 0.04910273 0.4253007  0.32749008 0.        ]
 [0.         0.66269189 0.53867361 0.73980084 0.26925793 0.        ]
 [0.         0.71145392 0.46609582 0.40620573 0.74380881 0.        ]
 [0.         0.50067306 0.41220718 0.94258054 0.64667963 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [6]:
import numpy as np

arr = np.arange(10, 61, 5)

print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

In [8]:
import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

arr_uppercase = np.char.upper(arr)
arr_lowercase = np.char.lower(arr)
arr_titlecase = np.char.title(arr)


print("Uppercase:", arr_uppercase)
print("Lowercase:", arr_lowercase)
print("Titlecase:", arr_titlecase)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [9]:
import numpy as np

words = np.array(["apple", "banana", "cherry"])

words_spaced = np.char.join(" ", words)

print(words_spaced)

['a p p l e' 'b a n a n a' 'c h e r r y']


**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [10]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result_add = array1 + array2
print("Addition:\n", result_add)

result_subtract = array1 - array2
print("Subtraction:\n", result_subtract)

result_multiply = array1 * array2
print("Multiplication:\n", result_multiply)

result_divide = array1 / array2
print("Division:\n", result_divide)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [11]:
import numpy as np

identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print("Identity matrix:\n", identity_matrix)
print("Diagonal elements:", diagonal_elements)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements: [1. 1. 1. 1. 1.]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array**

In [12]:
import numpy as np

random_numbers = np.random.randint(0, 1001, 100)

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

prime_numbers = [num for num in random_numbers if is_prime(num)]

print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [163, 991, 587, 139, 307, 541, 281, 157, 557, 349, 887, 997]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [13]:
import numpy as np

num_days = 31

daily_temps = np.random.randint(60, 90, num_days)

weekly_averages = []
for i in range(0, num_days, 7):
    week_temps = daily_temps[i:i+7]
    weekly_average = np.mean(week_temps)
    weekly_averages.append(weekly_average)

print("Weekly Averages:")
for i, average in enumerate(weekly_averages):
    print(f"Week {i+1}: {average:.2f}")

Weekly Averages:
Week 1: 79.43
Week 2: 76.00
Week 3: 74.29
Week 4: 72.86
Week 5: 78.33
